name: ⚙️

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        python-version:
          - "3.12"

    name: Test with Python ${{ matrix.python-version }} ${{ matrix.experimental-format }}

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install tox
      run: python -m pip install --upgrade tox tox-gh-actions
    - name: Run tox
      run: tox
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.xml
